// Shared page text used for the reader experience, ported verbatim from OpenShelf.dc.html.
// The prototype used one generic chapter for every book; every seeded book gets the same
// pages for now until per-book manuscripts are uploaded through a real submit flow.
export const READER_PAGES: string[] = [
  "The harbor kept its own hours. Long before the first ferry cleared the breakwater, the town was awake in its quiet way — kettles on, lamps low, the gulls rehearsing over the fish stalls.\n\nMara had learned to tell the weather by the sound of the ropes against the masts. Today they rang slow and even, which meant a kind sea, which meant her father would be late.",
  "He was always late on kind days. The sea forgave him nothing in winter, so in summer he took his time, letting the boat drift the last hundred yards as if arriving were a thing best done gently.\n\nFrom the window of the chandlery she watched the water take its color from the sky — grey first, then pewter, then a pale gold that no one had ever managed to paint honestly. The tourists tried every August. They left with canvases the color of egg yolk, and the town let them go with kindness.\n\nShe opened the ledger and began the day's small arithmetic.",
  "The bell above the door announced Mr. Abel, who did not buy anything and never had. He came for the chair by the stove and the right to an opinion about the weather.\n\n“Rain by Thursday,” he said, settling in.\n\n“The ropes say otherwise.”\n\n“The ropes are optimists.” He unfolded his newspaper, which was four days old and better for it. News, he liked to say, improved with keeping, like anything pickled.\n\nOutside, the ferry sounded its horn — once, politely, the way it did when the harbormaster's dog was asleep on the ramp again.",
  "By ten the fog had given up its argument with the sun and gone off to sulk beyond the point. The quay filled with the usual commerce: crates of ice, coils of rope, rumors.\n\nThe rumor that morning concerned the lighthouse. It had gone dark on Tuesday for the better part of an hour, and no one — not the keeper, not the electric board, not Mr. Abel, who held theories the way other men held mortgages — could say why.\n\n“An hour is nothing,” said the keeper, when pressed.\n\n“An hour is an hour,” said the town, which had been navigating by that light for ninety years.",
  "Mara's father came in on the noon tide with a thin catch and a thick silence. She knew the silence. It was the one he wore when he had seen something on the water he did not intend to discuss on land.\n\nShe let him unload. She let him coil the lines and hose the deck and hang his oilskins on the hook that had held them for thirty years. Then she put a mug of tea in his hands and waited, because waiting was the only net that ever caught him.",
  "“The light,” he said at last. “Tuesday night. We were off the point when it went.”\n\n“And?”\n\n“And the sea went with it.” He turned the mug in his hands. “Not the water. The sound of it. A whole minute, maybe two, quiet as a held breath. Birds up off the stacks all at once, and then the light came back and the sea came back, and nobody on that boat has said a word about it since.”\n\nThe stove ticked. Somewhere out on the quay a crate was set down harder than it needed to be.",
  "It is a particular talent of small towns to hold a mystery gently — to pass it hand to hand like a warm loaf, everyone taking a piece, no one taking the whole.\n\nBy evening the story had grown three versions and lost none of them. The schoolteacher favored instruments; the priest favored patience; Mr. Abel favored a theory involving the electric board, the county, and a heron with a grudge.\n\nMara wrote the day into the ledger the way her grandmother had taught her: fish, weights, weather. Then, in the margin, in pencil: the sea held its breath.",
  "Her father slept early. The town slept late. The lighthouse turned its long spoke of light over the water, steady as arithmetic, as if embarrassed by Tuesday and keen to make it up.\n\nMara sat on the chandlery step with the last of the tea and watched the beam go round. Somewhere beyond the breakwater the sea moved in its dark bed, keeping whatever it kept.\n\nTomorrow there would be ropes to sell and a ledger to fill, and Mr. Abel's rain, or not. Tonight there was only the light, counting the harbor over and over, and finding it — every pass — exactly where it had been left.",
];
